### ISSUE TITLE
Missing groups in categories.json result in internal server error when opening /catalog.rdf of website

### ISSUE THREAD

**Issue by rickelt** [rostock/ckanext-hro_dcatapde#1]
When the list of groups/categories in categories.json does not include every group on the actual website, it results in an internal server error, when trying to open the catalog.rdf of the website. 
e.g: I have a group called bevoelkerung, but it is missing or misspelled in the json file, I get the Error and the Error Logs mention a
`KeyError: u'bevoelkerung'`
Is there a way to circumvent this?
It is not great, whenever we have to change the groups on the frontend, to also have to change the json file.

**Comment by gdmhrogut** [comment]
There _has_ to be a mapping from CKAN groups/categories to [EU data themes](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme) _somewhere_ and the `categories.json` mapping file is thus the place for that.

Generally speaking, this piece of software is a custom implementation of DCAT-AP.de for _OpenData.HRO,_ the open data portal of the municipality of Rostock. Consequently, all the mappings in `ckanext/hro_dcatapde/mappings` are somewhat tailored to the needs of Rostock – most obviously in `ckanext/hro_dcatapde/mappings/geocodings.json`. There is no way round adopting those mapping files to your own needs.
