### ISSUE TITLE
possible to get 0 Errors for the DCAT-AP.de Validator

### ISSUE THREAD

**Issue by rickelt** [rostock/ckanext-hro_dcatapde#2]
Is it possible with this extension to get 0 Errors in the EU-Validator?
DCAT-AP.de Validator: https://www.itb.ec.europa.eu/shacl/dcat-ap.de/upload
(Github https://github.com/GovDataOfficial/DCAT-AP.de-SHACL-Validation/)
This Extension is really helpful to assign a license to a ressource, but I still have a few metadata missing, like publisher_name and publisher_email.

**Comment by gdmhrogut** [comment]
Well, I'm pretty sure it _would_ be possible if the [DCAT-AP.de Validator](https://www.itb.ec.europa.eu/shacl/dcat-ap.de/upload) _was_ working correctly and not mostly coughing up false negatives. This test for example…

![8932hfGEHJGFJZJZjgrj](https://user-images.githubusercontent.com/1705720/188393749-70ddd165-7e50-4c65-8777-337c16c808a9.png)

…leads to 10 errors supposing that `dct:language` is not an URI – but in fact it _is:_ `http://publications.europa.eu/resource/authority/language/DEU`.

With 7c1a44c I fixed the error that `dct:accessRights` was not returning an URI but a literal.
